imports:
  - php
  
filter:
  excluded-paths:
    - example/*
    - fixtures/*
    - vendor/*
    - src/Mage/*

tools:
  php_code_sniffer:
    config:
      standard: "PSR2"
    filter:
      excluded-paths: [ spec/*, features/*, src/Mage/* ]
  php_sim:
    filter:
      excluded-paths: [ spec/*, features/*, src/Mage/* ]
  php_changetracking: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer:
    filter:
      excluded-paths: [ spec/*, features/*, src/Mage/* ]
