imports:
  - php
  
filter:
  excluded_paths:
    - example/*
    - fixtures/*

tools:
  php_code_sniffer:
    config:
      standard: "PSR2"
  php_sim: true
  php_changetracking: true
  php_mess_detector: true
  php_pdepend: true
  php_analyzer: true

